development:
  adapter: postgresql
  encoding: unicode
  database: twitter_app_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: twitter_app_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: twitter_app_production
  pool: 5
  username: 
  password:
